### ISSUE TITLE
DSI Scholars - Environment set up

### ISSUE THREAD

**Issue by zhuyiming0816** [AIModelShare/aimodelshare#198]
I had no previous experience with AWS, so it took me a while for setting up the AWS and also configuring how to set up the playground using the credentials. I believe it would be helpful to create a button to connect the AI Model website with AWS and manage to skip some steps. 
I have uploaded the video of my first crack.

**Comment by AIModelShare** [comment]
-similar to other aws
confusing for first time user to connect to aws account

-didn't know where to start on front page

-add create button to send them direct to creation notebook
