### ISSUE TITLE
Instructions on Creating Playgrounds and Competitions

### ISSUE THREAD

**Issue by kevinhuang4** [AIModelShare/aimodelshare#199]
I spent some time on the website trying to find the instructions on creating a new playground, but I could only saw the other playgrounds that people created. Then, I searched "AI Model Share Create Playground" on google and found the "getting started tutorial". I think it would be better if there's a button on the playground page that leads to the "getting started instructions".

**Comment by AIModelShare** [comment]
-provide more obvious getting started link on front page
-on playground page link to getting started tutorial.  (link to deploy tab)
